[package]
name = "soroban-upgrades-cli"
description = "CLI and CI safety gate for Stellar Soroban contract upgrades"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "soroban-upgrades"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
soroban-upgrades-core = { version = "0.1.0-alpha.1", path = "../soroban-upgrades-core" }
